name: Security Scan and Upload to DefectDojo

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t "$IMAGE_NAME" .
        env:
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}

      - name: Run Trivy scan using Trivy Docker image
        run: |
          docker run --rm -v "$PWD:/work" aquasecurity/trivy:0.53.0 \
            image --format json -o /work/trivy-report.json "$IMAGE_NAME" || true
        env:
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}

      - name: Upload report to DefectDojo
        run: |
          ls -l
          echo "Uploading report to DefectDojo..."
          curl -v -X POST "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
            -F "scan_type=Trivy Scan" \
            -F "product_name=DevSecOps POC Application" \
            -F "engagement_name=GitHub Actions Trivy Scan" \
            -F "file=@trivy-report.json" \
            -F "active=true" \
            -F "verified=false" \
            -F "minimum_severity=Low"
